---
title: "data_for_regression_v2"
output: html_document
---

```{r setup}
options(scipen = 999)
library(purrr)
library(dplyr)
library(data.table)
```

# Data Preparation Notebook

Read in the salary and player data.

```{r}
# list files in data/salary/src directory
dir <- "data/salary/src"
salary_files_tmp <- list.files(dir)
salary_files <- paste0(dir, "/", salary_files_tmp)

# read in salary data
salary_df <- map_df(salary_files, fread) %>% 
    as_tibble()

# remove career rows
salary_df <- salary_df %>%
  filter(Season != "Career")

head(salary_df)
```

```{r}
# list files in data/gamelog/src directory
dir <- "data/gamelog/src/gamelogs/"
gamelog_files_tmp <- list.files(dir)
# remove files that start with a number
gamelog_files_tmp <- gamelog_files_tmp[!grepl("^[0-9]", gamelog_files_tmp)]
gamelog_files <- paste0(dir, "/", gamelog_files_tmp)

# read in gamelog data
# cast the GS column to character to avoid errors
gamelog_df <- map_df(gamelog_files, ~fread(.x) %>% mutate(across(.fns = as.character))) %>%
    as_tibble()
```
```{r}
head(gamelog_df)
```

We merge the two data sets on player id.

```{r}
# merge the two data sets
df <- gamelog_df %>% 
    inner_join(salary_df, by = c("player" = "player_id"))

head(df)
```

Now we also get some player-level data.

```{r}
# list files in data/players/src directory
dir <- "data/players/src/"
players_files_tmp <- list.files(dir)
players_files <- paste0(dir, "/", players_files_tmp)

# read in players data
players_df <- map_df(players_files,  ~fread(.x) %>% mutate(across(.fns = as.character))) %>%
    as_tibble()

# we must create a player id column from the player_href column
# this is the string between /a/ and .html 
# convert the height to numeric, from feet-inches to inches
players_df <- players_df %>% 
    mutate(
        player_id = stringr::str_extract(player_href, "(?<=/a/).*(?=\\.html)"),
        # get number before the dash and after the dash
        Ht = as.numeric(substr(Ht, 1, 1)) * 12 + as.numeric(substr(Ht, 3, 4))
    )
```
```{r}
summary(players_df$Ht)
```

We merge this to the main data set.

```{r}
# merge the two data sets
df2 <- df %>% 
    inner_join(players_df, by = c("player" = "player_id"))
```
Since the salary is a season-level statistic, we calculate season-level statistics for the game-level in-game statistics. 

```{r}
per_season_data_tmp <- df2 %>% 
    mutate(
        Age = substr(Age, 1, 2), # get first two characters of age to make numeric
        # convert salary to numeric, parsing out the $ and commas
        Salary = as.numeric(gsub("[$,]", "", Salary)),
        # convert the MP to numeric. Get minutes before the colon and seconds after the colon
        # convert minutes to seconds and add to seconds
        # if "Did Not Play" then set to 0
        MP = ifelse(MP == "Did Not Play", 0, MP),
        MP = as.numeric(substr(MP, 1, 2)) * 60 + as.numeric(substr(MP, 4, 5))
    ) %>%
    group_by(player,Season) %>%
      summarize(
        age = mean(as.numeric(Age)),
        tm = first(Tm),
        team = first(Team),
        pos = first(Pos),
        ht = mean(as.numeric(Ht)),
        wt = mean(as.numeric(Wt)),
        colleges = first(Colleges),
        g = sum(as.numeric(G), na.rm = TRUE),
        gs = sum(as.numeric(GS), na.rm = TRUE),
        mp = mean(as.numeric(MP), na.rm = TRUE),
        fg = mean(as.numeric(FG), na.rm = TRUE),
        fga = mean(as.numeric(FGA), na.rm = TRUE),
        fg_pct = mean(as.numeric(`FG%`), na.rm = TRUE),
        thr_pt = mean(as.numeric(`3P`), na.rm = TRUE),
        thr_pt_at = mean(as.numeric(`3PA`), na.rm = TRUE),
        thr_pt_pct = mean(as.numeric(`3P%`), na.rm = TRUE),
        ft = mean(as.numeric(FT), na.rm = TRUE),
        ft_at = mean(as.numeric(FTA), na.rm = TRUE),
        ft_pct = mean(as.numeric(`FT%`), na.rm = TRUE),
        orb = mean(as.numeric(ORB), na.rm = TRUE),
        drb = mean(as.numeric(DRB), na.rm = TRUE),
        trb = mean(as.numeric(TRB), na.rm = TRUE),
        ast = mean(as.numeric(AST), na.rm = TRUE),
        stl = mean(as.numeric(STL), na.rm = TRUE),
        blk = mean(as.numeric(BLK), na.rm = TRUE),
        tov = mean(as.numeric(TOV), na.rm = TRUE),
        pf = mean(as.numeric(PF), na.rm = TRUE),
        pts = mean(as.numeric(PTS), na.rm = TRUE),
        salary = mean(Salary, na.rm = TRUE),
    )

head(per_season_data_tmp)

# write tp csv
readr::write_csv(per_season_data_tmp, "data/per_season_data_v2.csv")
```