gamelogs_header = {
    "Rk": "rank", "G": 
    "season_game", 
    "Date": "date", 
    "Age": "age",
    "Tm": "team", 
    "Unnamed: 5": "location", 
    "Opp":"opponent", 
    "Unnamed: 7": "game_res", 
    "GS" : "game_started", 
    "MP" : "minutes_played", 
    "FG"  : "field_goals", 
    "FGA" : "field_goals_attempts", 
    "FG%" : "field_goals_pct", 
    "3P"  : "field_goals_3pt", 
    "3PA" : "field_goals_attempt_3pt", 
    "3P%" : "field_goals_pct_3pt", 
    "FT"  : "free_throws", 
    "FTA" : "free_throws_attempts", 
    "FT%" : "free_throws_pct", 
    "ORB" : "offensive_rebounds", 
    "DRB" : "defensive_rebounds", 
    "TRB" : "total_rebounds", 
    "AST" : "assists", 
    "STL" : "steals", 
    "BLK" : "blocks", 
    "TOV" : "turnovers", 
    "PF"  : "personal_fouls", 
    "PTS" : "points", 
    "GmSc": "game_score", 
    "+/-" : "score_diff",
}

player_header = {
    'Player': "player_name", 
    'From': "start_play_period", 
    'To': "end_play_period", 
    'Pos': "position", 
    'Ht': "height", 
    'Wt': "weight", 
    'Birth Date': 
    "birth_date", 
    'Colleges': "college", 
}

salary_header = {
    'Season': "season", 
    'Team': "og_team_name", 
    'Lg': "league", 
    'Salary': "salary", 
    'player_id': "player_id"
}

team_names = {
    "ORL": "Orlando Magic", 
    "DEN": "Denver Nuggets", 
    "CLE": "Cleveland Cavaliers", 
    "MIL": "Milwaukee Bucks", 
    "MIN": "Minnesota Timberwolves", 
    "SDR": "San Diego Rockets", 
    "INJ": "Indianapolis Jets", 
    "NJN": "New Jersey Nets", 
    "BOS": "Boston Celtics", 
    "CHS": "Charlotte Hornets", 
    "MIA": "Miami Heat", 
    "CHI": "Chicago Bulls", 
    "OKC": "Oklahoma City Thunder", 
    "HOU": "Houston Rockets", 
    "VAN": "Vancouver Grizzlies", 
    "SAC": "Sacramento Kings", 
    "DAL": "Dallas Mavericks", 
    "NYK": "New York Knicks", 
    "TOR": "Toronto Raptors", 
    "LAL": "Los Angeles Lakers", 
    "SEA": "Seattle SuperSonics", 
    "ATL": "Atlanta Hawks", 
    "MNL": "Minneapolis Lakers", 
    "CIN": "Cincinnati Royals", 
    "BAL": "Baltimore Bullets", 
    "PHO": "Phoenix Suns", 
    "PHI": "Philadelphia 76ers", 
    "SAS": "San Antonio Spurs", 
    "TRH": "Toronto Huskies", 
    "CLR": "Cleveland Rebels", 
    "WAS": "Washington Wizards", 
    "IND": "Indiana Pacers", 
    "BUF": "Buffalo Braves", 
    "DET": "Detroit Pistons", 
    "POR": "Portland Trail Blazers", 
    "LAC": "Los Angeles Clippers", 
    "FTW": "Fort Wayne Pistons", 
    "CHO": "Charlotte Bobcats", 
    "MEM": "Memphis Grizzlies", 
    "UTA": "Utah Jazz", 
    "STB": "St. Louis Bombers", 
    "NOH": "New Orleans Hornets", 
    "BRK": "Brooklyn Nets", 
    "SFW": "San Francisco Warriors", 
    "SDC": "San Diego Clippers", 
    "SYR": "Syracuse Nationals", 
    "STL": "St. Louis Hawks", 
    "GSW": "Golden State Warriors", 
    "NOJ": "New Orleans Jazz", 
    "WSB": "Washington Bullets", 
    "KCK": "Kansas City Kings",
    "BLB": "Baltimore Clippers", 
    "CHH": "Charlotte Hornets", 
    "MLH": "Milwaukee Hawks", 
    "NOP": "New Orleans Pelicans", 
    "KCO": "Kansas City-Omaha Kings", 
    "PHW": "Philadelphia Warriors", 
    "WSC": "Washington Capitols", 
    "WAT": "Waterloo Hawks", 
    "SHE": "Sheboygan Red Skins", 
    "ROC": "Rochester Royals", 
    "PRO": "Providence Steamrollers", 
    "CHA": "Charleston Lowgators", 
    "INO": "Indianapolis Olympians", 
    "DTF": "Detroit Falcons", 
    "NYN": "New York Nets", 
    "CHP": "Chicago Packers", 
    "NOK": "New Orleans/Oklahoma City Hornets", 
    "CAP": "Capital Bullets", 
    "CHZ": "Chicago Zephyrs", 
    "TRI": "Tri-Cities Blackhawks", 
    "DNN": "Denver Nuggets", 
    "PIT": "Pittsburgh Ironmen", 
    "SDS": "San Diego Sails", 
    "AND": "Anderson Packers", 
    "TEX": "Texas Chaparrals", 
    "KEN": "Kentucky Colonels", 
    "SDA": "San Diego Conquistadors", 
    "DLC": "Dallas Chaparrals", 
    "NYA": "New York Americans", 
    "DNR": "Denver Rockets", 
    "SSL": "St. Louis Spirits"
}


results_map = {"W": 1,"L": 0,}


game_started_map = {
    "0": 0, 
    "1": 1, 
    "Did Not Play": 0, 
    "Inactive": 0,
    "Not With Team": 0,
    "Did Not Dress": 0, 
    "0.0": 0, 
    "1.0": 1, 
    "Player Suspended": 0,
    "DNP": 0,
}

position_map = {
    'F': "forward", 
    'G': "guard", 
    'C-F': "center-forward", 
    'G-F': "guard-forward", 
    'F-C': "forward-center", 
    'C': "center", 
    'F-G': "forward-guard"
}